package com.example.novinshop_project.utils

const val TYPE_ONE="1"
const val TYPE_TWO="2"
const val CHART="chart"
const val COMPARE="compare"
const val PRODUCT_ONE="id1"
const val PRODUCT_TWO="id2"
const val PRODUCT_ID="id"
const val CATEGORY_ID="catId"
const val BRAND_ID="brandId"
const val YES="yes"
const val NO="no"
const val ADDRESS="address"
const val FAMILY="family"
const val WALLET="wallet"
const val DIRECT="direct"
const val ADDRESS_ID="addresId"
const val REFID="refId"
